sudo: false
language: node_js
node_js:
  - "8"

script:
  - npm run lint
  - npm run test

cache:
  directories:
    - node_modules

before_install:
- '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest'
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
