sudo: false
language: node_js
node_js:
  - "8"

script:
  - npm run lint
  - npm run test

cache:
  directories:
    - node_modules

before_install:
- '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest'
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

before_deploy:
  - git config --local user.name "ztoben"
  - git config --local user.email "zach.toben@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: dist/*
  skip_cleanup: true
  on:
    branch: master
    tags: true
